<?php

namespace Database\Seeders;

use App\Models\UserManagement\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'view-school' => [
                'name' => 'view-school',
                'guard_name' => 'web',
                'component' => 'MasterData:Schools',
                'description' => 'View Schools',
            ],
            'create-school' => [
                'name' => 'create-school',
                'guard_name' => 'web',
                'component' => 'MasterData:Schools',
                'description' => 'Create School',
            ],
            'edit-school' => [
                'name' => 'edit-school',
                'guard_name' => 'web',
                'component' => 'MasterData:Schools',
                'description' => 'Edit School',
            ],
            'delete-school' => [
                'name' => 'delete-school',
                'guard_name' => 'web',
                'component' => 'MasterData:Schools',
                'description' => 'Delete School',
            ],
            'view-college' => [
                'name' => 'view-college',
                'guard_name' => 'web',
                'component' => 'MasterData:Colleges',
                'description' => 'View Colleges',
            ],
            'create-college' => [
                'name' => 'create-college',
                'guard_name' => 'web',
                'component' => 'MasterData:Colleges',
                'description' => 'Create College',
            ],
            'edit-college' => [
                'name' => 'edit-college',
                'guard_name' => 'web',
                'component' => 'MasterData:Colleges',
                'description' => 'Edit College',
            ],
            'delete-college' => [
                'name' => 'delete-college',
                'guard_name' => 'web',
                'component' => 'MasterData:Colleges',
                'description' => 'Delete College',
            ],
            'view-universities' => [
                'name' => 'view-universities',
                'guard_name' => 'web',
                'component' => 'MasterData:Universities',
                'description' => 'View Universities',
            ],
            'create-universities' => [
                'name' => 'create-universities',
                'guard_name' => 'web',
                'component' => 'MasterData:Universities',
                'description' => 'Create Universities',
            ],
            'edit-universities' => [
                'name' => 'edit-universities',
                'guard_name' => 'web',
                'component' => 'MasterData:Universities',
                'description' => 'Edit Universities',
            ],
            'delete-universities' => [
                'name' => 'delete-universities',
                'guard_name' => 'web',
                'component' => 'MasterData:Universities',
                'description' => 'Delete Universities',
            ],
            'view-field-agent' => [
                'name' => 'view-field-agent',
                'guard_name' => 'web',
                'component' => 'MasterData:FieldAgents',
                'description' => 'View Field Agents',
            ],
            'create-field-agent' => [
                'name' => 'create-field-agent',
                'guard_name' => 'web',
                'component' => 'MasterData:FieldAgents',
                'description' => 'Create Field Agents',
            ],
            'edit-field-agent' => [
                'name' => 'edit-field-agent',
                'guard_name' => 'web',
                'component' => 'MasterData:FieldAgents',
                'description' => 'Edit Field Agents',
            ],
            'delete-field-agent' => [
                'name' => 'delete-field-agent',
                'guard_name' => 'web',
                'component' => 'MasterData:FieldAgents',
                'description' => 'Delete Field Agents',
            ],
            'view-role' => [
                'name' => 'view-role',
                'guard_name' => 'web',
                'component' => 'UserManagement:Roles',
                'description' => 'View Roles',
            ],
            'create-role' => [
                'name' => 'create-role',
                'guard_name' => 'web',
                'component' => 'UserManagement:Roles',
                'description' => 'Create Roles',
            ],
            'edit-role' => [
                'name' => 'edit-role',
                'guard_name' => 'web',
                'component' => 'UserManagement:Roles',
                'description' => 'Edit Role',
            ],
            'delete-role' => [
                'name' => 'delete-role',
                'guard_name' => 'web',
                'component' => 'UserManagement:Roles',
                'description' => 'Delete Role',
            ],
            'view-staff' => [
                'name' => 'view-staff',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'View Internal Staff',
            ],
            'edit-staff' => [
                'name' => 'edit-staff',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Edit Internal Staff',
            ],
            'delete-staff' => [
                'name' => 'delete-staff',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Delete Internal Staff',
            ],
            'create-staff' => [
                'name' => 'create-staff',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Create Internal Staff',
            ],
            'view-subscribers' => [
                'name' => 'view-subscribers',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'View Subscribers',
            ],
            'edit-subscribers' => [
                'name' => 'edit-subscribers',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Edit Subscribers',
            ],
            'upload-subscribers' => [
                'name' => 'upload-subscribers',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Upload Subscribers',
            ],
            'delete-subscribers' => [
                'name' => 'delete-subscribers',
                'guard_name' => 'web',
                'component' => 'UserManagement:Users',
                'description' => 'Delete Subscribers',
            ],
            'view-faq' => [
                'name' => 'view-faq',
                'guard_name' => 'web',
                'component' => 'MasterData:Faq',
                'description' => 'View Faq',
            ],
            'create-faq' => [
                'name' => 'create-faq',
                'guard_name' => 'web',
                'component' => 'MasterData:Faq',
                'description' => 'Create Faq',
            ],
            'edit-faq' => [
                'name' => 'edit-faq',
                'guard_name' => 'web',
                'component' => 'MasterData:Faq',
                'description' => 'Edit Faq',
            ],
            'delete-faq' => [
                'name' => 'delete-faq',
                'guard_name' => 'web',
                'component' => 'MasterData:Faq',
                'description' => 'Delete Faq',
            ],
            'view-faq_category' => [
                'name' => 'view-faq_category',
                'guard_name' => 'web',
                'component' => 'MasterData:FaqCategory',
                'description' => 'View Faq Category',
            ],
            'edit-faq_category' => [
                'name' => 'edit-faq_category',
                'guard_name' => 'web',
                'component' => 'MasterData:FaqCategory',
                'description' => 'Edit Faq Category',
            ],
            'create-faq_category' => [
                'name' => 'create-faq_category',
                'guard_name' => 'web',
                'component' => 'MasterData:FaqCategory',
                'description' => 'Create Faq Category',
            ],
            'delete-faq_category' => [
                'name' => 'delete-faq_category',
                'guard_name' => 'web',
                'component' => 'MasterData:FaqCategory',
                'description' => 'Delete Faq Category',
            ],
            'view-question_source' => [
                'name' => 'view-question_source',
                'guard_name' => 'web',
                'component' => 'MasterData:QuestionSource',
                'description' => 'View Question Source',
            ],
            'edit-question_source' => [
                'name' => 'edit-question_source',
                'guard_name' => 'web',
                'component' => 'MasterData:QuestionSource',
                'description' => 'Edit Question Source',
            ],
            'delete-question_source' => [
                'name' => 'delete-question_source',
                'guard_name' => 'web',
                'component' => 'MasterData:QuestionSource',
                'description' => 'Delete Question Source',
            ],
            'create-question_source' => [
                'name' => 'create-question_source',
                'guard_name' => 'web',
                'component' => 'MasterData:QuestionSource',
                'description' => 'Create Question Source',
            ],
            'view-downloadable-resource' => [
                'name' => 'view-downloadable-resource',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResources',
                'description' => 'View Downloadable Resources',
            ],
            'create-downloadable-resource' => [
                'name' => 'create-downloadable-resource',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResources',
                'description' => 'Create Downloadable Resources',
            ],
            'edit-downloadable-resource' => [
                'name' => 'edit-downloadable-resource',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResources',
                'description' => 'Edit Downloadable Resources',
            ],
            'delete-downloadable-resource' => [
                'name' => 'delete-downloadable-resource',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResources',
                'description' => 'Delete Downloadable Resources',
            ],
            'view-testimonials' => [
                'name' => 'view-testimonials',
                'guard_name' => 'web',
                'component' => 'MasterData:Testimonials',
                'description' => 'View Testimonials',
            ],
            'create-testimonial' => [
                'name' => 'create-testimonial',
                'guard_name' => 'web',
                'component' => 'MasterData:Testimonials',
                'description' => 'Create Testimonial',
            ],
            'edit-testimonial' => [
                'name' => 'edit-testimonial',
                'guard_name' => 'web',
                'component' => 'MasterData:Testimonials',
                'description' => 'Edit Testimonial',
            ],
            'delete-testimonial' => [
                'name' => 'delete-testimonial',
                'guard_name' => 'web',
                'component' => 'MasterData:Testimonials',
                'description' => 'Delete Testimonial',
            ],
            'view-media' => [
                'name' => 'view-media',
                'guard_name' => 'web',
                'component' => 'MasterData:Media',
                'description' => 'View Media',
            ],
            'create-media' => [
                'name' => 'create-media',
                'guard_name' => 'web',
                'component' => 'MasterData:media',
                'description' => 'Create media',
            ],
            'edit-media' => [
                'name' => 'edit-media',
                'guard_name' => 'web',
                'component' => 'MasterData:media',
                'description' => 'Edit media',
            ],
            'delete-media' => [
                'name' => 'delete-media',
                'guard_name' => 'web',
                'component' => 'MasterData:media',
                'description' => 'Delete media',
            ],
            'view-all-leads' => [
                'name' => 'view-all-leads',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'View all Leads',
            ],
            'view-assigned-leads' => [
                'name' => 'view-assigned-leads',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'View Assigned Leads',
            ],
            'create-lead' => [
                'name' => 'create-lead',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Create Lead',
            ],
            'edit-lead' => [
                'name' => 'edit-lead',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Edit Assigned Leads',
            ],
            'delete-lead' => [
                'name' => 'delete-lead',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Delete lead',
            ],
            'assign-agent' => [
                'name' => 'assign-agent',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Assign Agent',
            ],
            'import-leads' => [
                'name' => 'import-leads',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Import Leads',
            ],
            'view-lead_source' => [
                'name' => 'view-lead_source',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'View lead sources',
            ],
            'create-lead_source' => [
                'name' => 'create-lead_source',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Create Lead sources',
            ],
            'edit-lead_source' => [
                'name' => 'edit-lead_source',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Edit Lead sources',
            ],
            'delete-lead_source' => [
                'name' => 'delete-lead_source',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Leads',
                'description' => 'Delete Lead Sources',
            ],
            'view-user_category' => [
                'name' => 'view-user_category',
                'guard_name' => 'web',
                'component' => 'UserManagement:UserCategory',
                'description' => 'View user category',
            ],
            'edit-user_category' => [
                'name' => 'edit-user_category',
                'guard_name' => 'web',
                'component' => 'UserManagement:UserCategory',
                'description' => 'Edit user category',
            ],
            'delete-user_category' => [
                'name' => 'delete-user_category',
                'guard_name' => 'web',
                'component' => 'UserManagement:UserCategory',
                'description' => 'Delete user category',
            ],
            'create-user_category' => [
                'name' => 'create-user_category',
                'guard_name' => 'web',
                'component' => 'UserManagement:UserCategory',
                'description' => 'Create user category',
            ],
            'view-resource_type' => [
                'name' => 'view-resource_type',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResourcesCategory',
                'description' => 'View DownloadableResources',
            ],
            'edit-resource_type' => [
                'name' => 'edit-resource_type',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResourcesCategory',
                'description' => 'Edit Downloadable Resources',
            ],
            'delete-resource_type' => [
                'name' => 'delete-resource_type',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResourcesCategory',
                'description' => 'Delete Downloadable Resources',
            ],
            'create-resource_type' => [
                'name' => 'create-resource_type',
                'guard_name' => 'web',
                'component' => 'ContentManagement:DownloadableResourcesCategory',
                'description' => 'Create Downloadable Resources',
            ],
            'view-article_category' => [
                'name' => 'view-article_category',
                'guard_name' => 'web',
                'component' => 'Blogs:ArticlesCategory',
                'description' => 'View Article Categories',
            ],
            'edit-article_category' => [
                'name' => 'edit-article_category',
                'guard_name' => 'web',
                'component' => 'Blogs:ArticlesCategory',
                'description' => 'Edit Article Categories',
            ],
            'create-article_category' => [
                'name' => 'create-article_category',
                'guard_name' => 'web',
                'component' => 'Blogs:ArticlesCategory',
                'description' => 'Create Article Categories',
            ],
            'delete-article_category' => [
                'name' => 'delete-article_category',
                'guard_name' => 'web',
                'component' => 'Blogs:ArticlesCategory',
                'description' => 'Delete Article Categories',
            ],
            'view-current-affair_category' => [
                'name' => 'view-current-affair_category',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairsCategory',
                'description' => 'View Current Affair Categories',
            ],
            'edit-current-affair_category' => [
                'name' => 'edit-current-affair_category',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairsCategory',
                'description' => 'Edit Current Affair Categories',
            ],
            'create-current-affair_category' => [
                'name' => 'create-current-affair_category',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairsCategory',
                'description' => 'Create Current Affair Categories',
            ],
            'delete-current-affair_category' => [
                'name' => 'delete-current-affair_category',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairsCategory',
                'description' => 'Delete Current Affair Categories',
            ],
            'view-article' => [
                'name' => 'view-article',
                'guard_name' => 'web',
                'component' => 'Blogs:Articles',
                'description' => 'View Articles',
            ],
            'create-article' => [
                'name' => 'create-article',
                'guard_name' => 'web',
                'component' => 'Blogs:Articles',
                'description' => 'Create Articles',
            ],
            'edit-article' => [
                'name' => 'edit-article',
                'guard_name' => 'web',
                'component' => 'Blogs:Articles',
                'description' => 'Edit Articles',
            ],
            'delete-article' => [
                'name' => 'delete-article',
                'guard_name' => 'web',
                'component' => 'Blogs:Articles',
                'description' => 'Delete Articles',
            ],
            'view-current-affair' => [
                'name' => 'view-current-affair',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairs',
                'description' => 'View Current Affairs',
            ],
            'edit-current-affair' => [
                'name' => 'edit-current-affair',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairs',
                'description' => 'Edit Current Affairs',
            ],
            'create-current-affair' => [
                'name' => 'create-current-affair',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairs',
                'description' => 'Create Current Affairs',
            ],
            'delete-current-affair' => [
                'name' => 'delete-current-affair',
                'guard_name' => 'web',
                'component' => 'Blogs:CurrentAffairs',
                'description' => 'Delete Current Affairs',
            ],
            'create-blog-author' => [
                'name' => 'create-blog-author',
                'guard_name' => 'web',
                'component' => 'Blogs:Author',
                'description' => 'Create Blog Authors',
            ],
            'edit-blog-author' => [
                'name' => 'edit-blog-author',
                'guard_name' => 'web',
                'component' => 'Blogs:Author',
                'description' => 'Edit Blog Authors',
            ],
            'delete-blog-author' => [
                'name' => 'delete-blog-author',
                'guard_name' => 'web',
                'component' => 'Blogs:Author',
                'description' => 'Delete Blog Authors',
            ],
            'view-blog-author' => [
                'name' => 'view-blog-author',
                'guard_name' => 'web',
                'component' => 'Blogs:Author',
                'description' => 'View Blog Authors',
            ],
            'view-settings' => [
                'name' => 'view-settings',
                'guard_name' => 'web',
                'component' => 'SiteSettings',
                'description' => 'View Site Settings',
            ],
            'view-job-postings' => [
                'name' => 'view-job-postings',
                'guard_name' => 'web',
                'component' => 'Career:JobPostings',
                'description' => 'View Job Postings',
            ],
            'edit-job-postings' => [
                'name' => 'edit-job-postings',
                'guard_name' => 'web',
                'component' => 'Career:JobPostings',
                'description' => 'Edit Job Postings',
            ],
            'create-job-postings' => [
                'name' => 'create-job-postings',
                'guard_name' => 'web',
                'component' => 'Career:JobPostings',
                'description' => 'Create Job Postings',
            ],
            'delete-job-postings' => [
                'name' => 'delete-job-postings',
                'guard_name' => 'web',
                'component' => 'Career:JobPostings',
                'description' => 'Delete Job Postings',
            ],
            'view-job_category' => [
                'name' => 'view-job_category',
                'guard_name' => 'web',
                'component' => 'Career:JobCategory',
                'description' => 'View Job Category',
            ],
            'edit-job_category' => [
                'name' => 'edit-job_category',
                'guard_name' => 'web',
                'component' => 'Career:JobCategory',
                'description' => 'Edit Job Category',
            ],
            'delete-job_category' => [
                'name' => 'delete-job_category',
                'guard_name' => 'web',
                'component' => 'Career:JobCategory',
                'description' => 'Delete Job Category',
            ],
            'create-job_category' => [
                'name' => 'create-job_category',
                'guard_name' => 'web',
                'component' => 'Career:JobCategory',
                'description' => 'Create Job Category',
            ],
            'view-sms_template' => [
                'name' => 'view-sms_template',
                'guard_name' => 'web',
                'component' => 'Notifications:SmsTemplate',
                'description' => 'View SMS Template',
            ],
            'edit-sms_template' => [
                'name' => 'edit-sms_template',
                'guard_name' => 'web',
                'component' => 'Notifications:SmsTemplate',
                'description' => 'Edit SMS Template',
            ],
            'delete-sms_template' => [
                'name' => 'delete-sms_template',
                'guard_name' => 'web',
                'component' => 'Notifications:SmsTemplate',
                'description' => 'Delete SMS Template',
            ],
            'create-sms_template' => [
                'name' => 'create-sms_template',
                'guard_name' => 'web',
                'component' => 'Notifications:SmsTemplate',
                'description' => 'Create SMS Template',
            ],
            'view-email_template' => [
                'name' => 'view-email_template',
                'guard_name' => 'web',
                'component' => 'Notifications:EmailTemplate',
                'description' => 'View Email Template',
            ],
            'edit-email_template' => [
                'name' => 'edit-email_template',
                'guard_name' => 'web',
                'component' => 'Notifications:EmailTemplate',
                'description' => 'Edit Email Template',
            ],
            'delete-email_template' => [
                'name' => 'delete-email_template',
                'guard_name' => 'web',
                'component' => 'Notifications:EmailTemplate',
                'description' => 'Delete Email Template',
            ],
            'create-email_template' => [
                'name' => 'create-email_template',
                'guard_name' => 'web',
                'component' => 'Notifications:EmailTemplate',
                'description' => 'Create Email Template',
            ],
            'view-sms_log' => [
                'name' => 'view-sms_log',
                'guard_name' => 'web',
                'component' => 'Notifications:SmsLog',
                'description' => 'View SMS Log',
            ],
            'view-email_log' => [
                'name' => 'view-email_log',
                'guard_name' => 'web',
                'component' => 'Notifications:EmailLog',
                'description' => 'View Email Log',
            ],
            'view-countrycode' => [
                'name' => 'view-countrycode',
                'guard_name' => 'web',
                'component' => 'MasterData:CountryCode',
                'description' => 'View CountryCode',
            ],
            'create-countrycode' => [
                'name' => 'create-countrycode',
                'guard_name' => 'web',
                'component' => 'MasterData:CountryCode',
                'description' => 'Create CountryCode',
            ],
            'edit-countrycode' => [
                'name' => 'edit-countrycode',
                'guard_name' => 'web',
                'component' => 'MasterData:CountryCode',
                'description' => 'Edit CountryCode',
            ],
            'delete-countrycode' => [
                'name' => 'delete-countrycode',
                'guard_name' => 'web',
                'component' => 'MasterData:CountryCode',
                'description' => 'Delete CountryCode',
            ],
            'view-hierarchy' => [
                'name' => 'view-hierarchy',
                'guard_name' => 'web',
                'component' => 'MasterData:Hierarchy',
                'description' => 'View Hierarchies',
            ],
            'create-hierarchy' => [
                'name' => 'create-hierarchy',
                'guard_name' => 'web',
                'component' => 'MasterData:Hierarchy',
                'description' => 'Create Hierarchies',
            ],
            'edit-hierarchy' => [
                'name' => 'edit-hierarchy',
                'guard_name' => 'web',
                'component' => 'MasterData:Hierarchy',
                'description' => 'Edit Hierarchies',
            ],
            'delete-hierarchy' => [
                'name' => 'delete-hierarchy',
                'guard_name' => 'web',
                'component' => 'MasterData:Hierarchy',
                'description' => 'Delete Hierarchies',
            ],
            'view-coupons' => [
                'name' => 'view-coupons',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Coupons',
                'description' => 'View Coupon Codes',
            ],
            'create-coupon' => [
                'name' => 'create-coupon',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Coupons',
                'description' => 'Create Coupon Codes',
            ],
            'edit-coupon' => [
                'name' => 'edit-coupon',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Coupons',
                'description' => 'Edit Coupon Codes',
            ],
            'delete-coupon' => [
                'name' => 'delete-coupon',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Coupons',
                'description' => 'Delete Coupon Codes',
            ],
            'view-website-pages' => [
                'name' => 'view-website-pages',
                'guard_name' => 'web',
                'component' => 'Website:Pages',
                'description' => 'View Website Pages',
            ],
            'create-website-pages' => [
                'name' => 'create-website-pages',
                'guard_name' => 'web',
                'component' => 'Website:Pages',
                'description' => 'Create Website Pages',
            ],
            'edit-website-pages' => [
                'name' => 'edit-website-pages',
                'guard_name' => 'web',
                'component' => 'Website:Pages',
                'description' => 'Edit Website Pages',
            ],
            'delete-website-pages' => [
                'name' => 'delete-website-pages',
                'guard_name' => 'web',
                'component' => 'Website:Pages',
                'description' => 'Delete Website Pages',
            ],
            'design-website-pages' => [
                'name' => 'design-website-pages',
                'guard_name' => 'web',
                'component' => 'Website:Pages',
                'description' => 'Design Website Pages',
            ],
            'view-webinar_category' => [
                'name' => 'view-webinar_category',
                'guard_name' => 'web',
                'component' => 'ContentManagement:WebinarCategory',
                'description' => 'View Webinar Categories',
            ],
            'edit-webinar_category' => [
                'name' => 'edit-webinar_category',
                'guard_name' => 'web',
                'component' => 'ContentManagement:WebinarCategory',
                'description' => 'Edit Webinar Categories',
            ],
            'create-webinar_category' => [
                'name' => 'create-webinar_category',
                'guard_name' => 'web',
                'component' => 'ContentManagement:WebinarCategory',
                'description' => 'Create Webinar Categories',
            ],
            'delete-webinar_category' => [
                'name' => 'delete-webinar_category',
                'guard_name' => 'web',
                'component' => 'ContentManagement:WebinarCategory',
                'description' => 'Delete Webinar Categories',
            ],
            'view-webinar' => [
                'name' => 'view-webinar',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Webinar',
                'description' => 'View Webinar',
            ],
            'edit-webinar' => [
                'name' => 'edit-webinar',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Webinar',
                'description' => 'Edit Webinar',
            ],
            'create-webinar' => [
                'name' => 'create-webinar',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Webinar',
                'description' => 'Create Webinar',
            ],
            'delete-webinar' => [
                'name' => 'delete-webinar',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Webinar',
                'description' => 'Delete Webinar',
            ],
            'view-studymaterial' => [
                'name' => 'view-studymaterial',
                'guard_name' => 'web',
                'component' => 'Content:StudyMaterial',
                'description' => 'View Content Study Material',
            ],
            'create-studymaterial' => [
                'name' => 'create-studymaterial',
                'guard_name' => 'web',
                'component' => 'Content:StudyMaterial',
                'description' => 'View  Study Material',
            ],
            'edit-studymaterial' => [
                'name' => 'edit-studymaterial',
                'guard_name' => 'web',
                'component' => 'Content:StudyMaterial',
                'description' => 'View  Study Material',
            ],
            'delete-studymaterial' => [
                'name' => 'delete-studymaterial',
                'guard_name' => 'web',
                'component' => 'Content:StudyMaterial',
                'description' => 'Delete Study Material',
            ],
            'create-orders' => [
                'name' => 'create-orders',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Orders',
                'description' => 'Create Orders',
            ],
            'view-orders' => [
                'name' => 'view-orders',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Orders',
                'description' => 'View Orders',
            ],
            'edit-orders' => [
                'name' => 'edit-orders',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Orders',
                'description' => 'Edit Orders',
            ],
            'create-notification-settings' => [
                'name' => 'create-notification-settings',
                'guard_name' => 'web',
                'component' => 'Notifications:Settings',
                'description' => 'Create Notification Setting',
            ],
            'edit-notification-settings' => [
                'name' => 'edit-notification-settings',
                'guard_name' => 'web',
                'component' => 'Notifications:Settings',
                'description' => 'Edit Notification Setting',
            ],
            'delete-notification-settings' => [
                'name' => 'delete-notification-settings',
                'guard_name' => 'web',
                'component' => 'Notifications:Settings',
                'description' => 'Delete Notification Setting',
            ],
            'view-package' => [
                'name' => 'view-package',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Packages',
                'description' => 'View Packages',
            ],
            'create-package' => [
                'name' => 'create-package',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Packages',
                'description' => 'Create Packages',
            ],
            'edit-package' => [
                'name' => 'edit-package',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Packages',
                'description' => 'Edit Packages',
            ],
            'delete-package' => [
                'name' => 'delete-package',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Packages',
                'description' => 'Delete Packages',
            ],
            'view-enrollments' => [
                'name' => 'view-enrollments',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Enrollments',
                'description' => 'View Enrollments',
            ],
            'delete-enrollments' => [
                'name' => 'delete-enrollments',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Enrollments',
                'description' => 'View Enrollments',
            ],
            'view-job-applications' => [
                'name' => 'view-job-applications',
                'guard_name' => 'web',
                'component' => 'Career:JobApplications',
                'description' => 'View Job Postings',
            ],
            'create-job-applications' => [
                'name' => 'create-job-applications',
                'guard_name' => 'web',
                'component' => 'Career:JobApplications',
                'description' => 'Create Job Applications',
            ],
            'edit-job-applications' => [
                'name' => 'edit-job-applications',
                'guard_name' => 'web',
                'component' => 'Career:JobApplications',
                'description' => 'Edit Job Applications',
            ],
            'delete-job-applications' => [
                'name' => 'delete-job-applications',
                'guard_name' => 'web',
                'component' => 'Career:JobApplications',
                'description' => 'Delete Job Applications',
            ],
            'view-transactions' => [
                'name' => 'view-transactions',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Transactions',
                'description' => 'View Transactions',
            ],
            'view-purchase-information' => [
                'name' => 'view-purchase-information',
                'guard_name' => 'web',
                'component' => 'UserManagement:PurchaseInformation',
                'description' => 'View Purchase Information',
            ],
            'view-lead-response' => [
                'name' => 'view-lead-response',
                'guard_name' => 'web',
                'component' => 'Marketing:LeadResponse',
                'description' => 'View Lead Response',
            ],
            'edit-lead-response' => [
                'name' => 'edit-lead-response',
                'guard_name' => 'web',
                'component' => 'Marketing:LeadResponse',
                'description' => 'Edit  Lead Response',
            ],
            'delete-lead-response' => [
                'name' => 'delete-lead-response',
                'guard_name' => 'web',
                'component' => 'Marketing:LeadResponse',
                'description' => 'Delete  Lead Response',
            ],
            'view-call-history' => [
                'name' => 'view-call-history',
                'guard_name' => 'web',
                'component' => 'Marketing:CallHistory',
                'description' => 'View Call History',
            ],

            'view-video_category' => [
                'name' => 'view-video_category',
                'guard_name' => 'web',
                'component' => 'MasterData:VideoCategory',
                'description' => 'View Video Category',
            ],
            'edit-video_category' => [
                'name' => 'edit-video_category',
                'guard_name' => 'web',
                'component' => 'MasterData:VideoCategory',
                'description' => 'Edit Video Category',
            ],
            'create-video_category' => [
                'name' => 'create-video_category',
                'guard_name' => 'web',
                'component' => 'MasterData:VideoCategory',
                'description' => 'Create Video Category',
            ],
            'delete-video_category' => [
                'name' => 'delete-video_category',
                'guard_name' => 'web',
                'component' => 'MasterData:VideoCategory',
                'description' => 'Delete Video Category',
            ],
            'view-guruvandanam_entries' => [
                'name' => 'view-guruvandanam_entries',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Guruvandanam',
                'description' => 'View Guruvandanam Entries',
            ],
            'view-videolist' => [
                'name' => 'view-videolist',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Guruvandanam',
                'description' => 'View Video List',
            ],
            'create-videolist' => [
                'name' => 'create-videolist',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Guruvandanam',
                'description' => 'Create Video List',
            ],
            'edit-videolist' => [
                'name' => 'edit-videolist',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Guruvandanam',
                'description' => 'Edit Video List',
            ],
            'delete-videolist' => [
                'name' => 'delete-videolist',
                'guard_name' => 'web',
                'component' => 'ContentManagement:Guruvandanam',
                'description' => 'Delete Video List',
            ],
            'create-batch' => [
                'name' => 'create-batch',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Batches',
                'description' => 'Create Batch',
            ],
            'edit-batch' => [
                'name' => 'edit-batch',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Batches',
                'description' => 'Edit Batch',
            ],
            'delete-batch' => [
                'name' => 'delete-batch',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Batches',
                'description' => 'Delete Batch',
            ],
            'create-pricing' => [
                'name' => 'create-pricing',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Pricing',
                'description' => 'Create Pricing',
            ],
            'edit-pricing' => [
                'name' => 'edit-pricing',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Pricing',
                'description' => 'Edit Pricing',
            ],
            'delete-pricing' => [
                'name' => 'delete-pricing',
                'guard_name' => 'web',
                'component' => 'Ecommerce:Pricing',
                'description' => 'Delete Pricing',
            ],
            'view-cloned-course' => [
                'name' => 'view-cloned-course',
                'guard_name' => 'web',
                'component' => 'MasterData:Cloned Courses',
                'description' => 'View Cloned Courses',
            ],
            'view-sap-data' => [
                'name' => 'view-sap-data',
                'guard_name' => 'web',
                'component' => 'Ecommerce:SAP Data',
                'description' => 'View SAP Data',
            ],
            'edit-sap-data' => [
                'name' => 'edit-sap-data',
                'guard_name' => 'web',
                'component' => 'Ecommerce:SAP Data',
                'description' => 'Edit SAP Data',
            ],
            'view-contact-requests' => [
                'name' => 'view-contact-requests',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Contact Requests',
                'description' => 'View Contact Requests',
            ],
            'view-newsletter-subscriptions' => [
                'name' => 'view-newsletter-subscriptions',
                'guard_name' => 'web',
                'component' => 'LeadManagement:Newsleter Subscriptions',
                'description' => 'View Newsleter Subscriptions',
            ],
        ];

        foreach ($permissions as $key => $permission) {
            $permission_id = Permission::updateOrCreate([
                'name' => $key,
            ], $permission);
        }
    }
}
