<?php

namespace Database\Seeders;

use App\Models\UserManagement\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $roles = [
            'administrator' => [
                'name' => 'administrator',
                'fullname' => 'Administrator',
                'description' => 'Manages everything on the site',
                'permissions' => [
                    'view-school',
                    'create-school',
                    'edit-school',
                    'delete-school',
                    'view-college',
                    'create-college',
                    'edit-college',
                    'delete-college',
                    'view-universities',
                    'create-universities',
                    'edit-universities',
                    'delete-universities',
                    'view-field-agent',
                    'create-field-agent',
                    'edit-field-agent',
                    'delete-field-agent',
                    'view-testimonials',
                    'create-testimonial',
                    'edit-testimonial',
                    'delete-testimonial',
                    'view-media',
                    'create-media',
                    'edit-media',
                    'delete-media',
                    'view-role',
                    'create-role',
                    'edit-role',
                    'delete-role',
                    'view-staff',
                    'create-staff',
                    'edit-staff',
                    'delete-staff',
                    'view-subscribers',
                    'edit-subscribers',
                    'upload-subscribers',
                    'delete-subscribers',
                    'view-faq',
                    'create-faq',
                    'edit-faq',
                    'delete-faq',
                    'view-faq_category',
                    'edit-faq_category',
                    'create-faq_category',
                    'delete-faq_category',
                    'view-question_source',
                    'edit-question_source',
                    'delete-question_source',
                    'create-question_source',
                    'view-downloadable-resource',
                    'create-downloadable-resource',
                    'edit-downloadable-resource',
                    'delete-downloadable-resource',
                    'view-all-leads',
                    'create-lead',
                    'edit-lead',
                    'delete-lead',
                    'assign-agent',
                    'import-leads',
                    'view-lead_source',
                    'create-lead_source',
                    'edit-lead_source',
                    'delete-lead_source',
                    'view-user_category',
                    'edit-user_category',
                    'delete-user_category',
                    'create-user_category',
                    'view-resource_type',
                    'edit-resource_type',
                    'delete-resource_type',
                    'create-resource_type',
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'delete-article_category',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'delete-current-affair_category',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'delete-article',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'delete-current-affair',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-blog-author',
                    'delete-blog-author',
                    'view-settings',
                    'view-job-postings',
                    'edit-job-postings',
                    'create-job-postings',
                    'delete-job-postings',
                    'delete-job_category',
                    'view-job_category',
                    'edit-job_category',
                    'create-job_category',
                    'view-sms_template',
                    'edit-sms_template',
                    'delete-sms_template',
                    'create-sms_template',
                    'view-email_template',
                    'edit-email_template',
                    'delete-email_template',
                    'create-email_template',
                    'view-sms_log',
                    'view-email_log',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'delete-hierarchy',
                    'view-countrycode',
                    'create-countrycode',
                    'edit-countrycode',
                    'delete-countrycode',
                    'view-coupons',
                    'create-coupon',
                    'edit-coupon',
                    'delete-coupon',
                    'view-website-pages',
                    'create-website-pages',
                    'edit-website-pages',
                    'design-website-pages',
                    'delete-website-pages',
                    'view-webinar_category',
                    'edit-webinar_category',
                    'create-webinar_category',
                    'delete-webinar_category',
                    'view-webinar',
                    'edit-webinar',
                    'create-webinar',
                    'delete-webinar',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                    'delete-studymaterial',
                    'create-orders',
                    'view-orders',
                    'edit-orders',
                    'create-notification-settings',
                    'edit-notification-settings',
                    'delete-notification-settings',
                    'view-package',
                    'create-package',
                    'edit-package',
                    'delete-package',
                    'view-enrollments',
                    'delete-enrollments',
                    'view-job-applications',
                    'create-job-applications',
                    'edit-job-applications',
                    'delete-job-applications',
                    'view-transactions',
                    'view-purchase-information',
                    'view-lead-response',
                    'edit-lead-response',
                    'delete-lead-response',
                    'view-call-history',
                    'view-guruvandanam_entries',
                    'view-video_category',
                    'edit-video_category',
                    'create-video_category',
                    'delete-video_category',
                    'view-videolist',
                    'create-videolist',
                    'edit-videolist',
                    'delete-videolist',
                    'create-batch',
                    'edit-batch',
                    'delete-batch',
                    'create-pricing',
                    'edit-pricing',
                    'delete-pricing',
                    'view-cloned-course',
                    'view-sap-data',
                    'edit-sap-data',
                    'view-contact-requests',
                    'view-newsletter-subscriptions',
                ],
            ],
            'moderator' => [
                'name' => 'moderator',
                'fullname' => 'Moderator',
                'description' => 'Moderator',
                'permissions' => [
                    'view-school',
                    'create-school',
                    'edit-school',
                    'view-college',
                    'create-college',
                    'edit-college',
                    'view-universities',
                    'create-universities',
                    'edit-universities',
                    'view-field-agent',
                    'create-field-agent',
                    'edit-field-agent',
                    'view-staff',
                    'create-staff',
                    'edit-staff',
                    'view-downloadable-resource',
                    'create-downloadable-resource',
                    'edit-downloadable-resource',
                    'create-website-pages',
                    'edit-website-pages',
                    'design-website-pages',
                    'view-faq',
                    'create-faq',
                    'edit-faq',
                    'view-faq_category',
                    'edit-faq_category',
                    'create-faq_category',
                    'view-assigned-leads',
                    'create-lead',
                    'assign-agent',
                    'import-leads',
                    'view-lead_source',
                    'create-lead_source',
                    'edit-lead_source',
                    'create-email_template',
                    'edit-email_template',
                    'create-sms_template',
                    'edit-sms_template',
                    'view-sms_log',
                    'view-email_log',
                    'create-notification-settings',
                    'edit-notification-settings',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-blog-author',
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'view-package',
                    'create-package',
                    'edit-package',
                    'view-enrollments',
                    'view-job-applications',
                    'create-job-applications',
                    'edit-job-applications',
                    'view-transactions',
                    'view-coupons',
                    'create-coupon',
                    'edit-coupon',
                    'view-orders',
                    'view-purchase-information',
                    'view-lead-response',
                    'edit-lead-response',
                    'view-call-history',
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                    'view-testimonials',
                    'create-testimonial',
                    'edit-testimonial',
                    'view-media',
                    'create-media',
                    'edit-media',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'view-settings',
                    'view-job-postings',
                    'edit-job-postings',
                    'create-job-postings',
                    'view-job_category',
                    'edit-job_category',
                    'create-job_category',
                    'view-sms_template',
                    'edit-sms_template',
                    'create-sms_template',
                    'view-email_template',
                    'edit-email_template',
                    'create-email_template',
                    'create-countrycode',
                    'edit-countrycode',
                    'view-webinar_category',
                    'edit-webinar_category',
                    'create-webinar_category',
                    'view-webinar',
                    'edit-webinar',
                    'create-webinar',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                    'create-batch',
                    'edit-batch',
                    'create-pricing',
                    'edit-pricing', 
                    'view-cloned-course',
                    'view-role',
                    'create-role',
                    'edit-role', 
                ],
            ],
            'blog-writer' => [
                'name' => 'blog-writer',
                'fullname' => 'Blog Writer',
                'description' => 'Blog Writer',
                'permissions' => [
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-blog-author',
                    'view-job-postings',
                    'edit-job-postings',
                    'create-job-postings',
                    'view-job_category',
                    'edit-job_category',
                    'create-job_category',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                ],
            ],
            'cclead' => [
                'name' => 'cclead',
                'fullname' => 'CC Lead',
                'description' => 'CC Lead',
                'permissions' => [
                    'view-downloadable-resource',
                    'import-leads',
                    'view-all-leads',
                    'create-lead',
                    'edit-lead',
                    'assign-agent',
                    'view-lead_source',
                    'create-lead_source',
                    'edit-lead_source',
                    'view-field-agent',
                    'create-field-agent',
                    'edit-field-agent',
                    'view-subscribers',
                    'edit-subscribers',
                    'upload-subscribers',
                    'view-faq',
                    'view-faq_category',
                    'view-assigned-leads',
                    'view-sms_log',
                    'view-email_log',
                    'view-enrollments',
                    'view-transactions',
                    'view-coupons',
                    'create-coupon',
                    'edit-coupon',
                    'view-orders',
                    'view-purchase-information',
                    'view-lead-response',
                    'edit-lead-response',
                    'view-call-history',
                    'view-testimonials',
                    'view-sms_template',
                    'view-email_template',
                    'view-package',
                ],
            ],
            'ccagent' => [
                'name' => 'ccagent',
                'fullname' => 'CC Agent',
                'description' => 'CC Agent',
                'permissions' => [
                    'view-downloadable-resource',
                    'view-assigned-leads',
                    'view-field-agent',
                    'create-field-agent',
                    'edit-field-agent',
                    'view-subscribers',
                    'edit-subscribers',
                    'upload-subscribers',
                    'view-faq',
                    'view-faq_category',
                    'create-lead',
                    'view-enrollments',
                    'view-coupons',
                    'create-coupon',
                    'view-orders',
                    'view-lead-response',
                    'view-purchase-information',
                    'view-call-history',
                    'edit-lead',
                    'view-lead_source',
                ],
            ],
            'expert' => [
                'name' => 'expert',
                'fullname' => 'Expert',
                'description' => 'Expert',
                'permissions' => [
                    'view-school',
                ],
            ],
            'test-center-expert' => [
                'name' => 'test-center-expert',
                'fullname' => 'Test Center Expert',
                'description' => 'Test Center Expert',
                'permissions' => [
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                    'delete-question_source',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                ],
            ],
            'creator' => [
                'name' => 'creator',
                'fullname' => 'Creator',
                'description' => 'Creator',
                'permissions' => [
                    'view-school',
                ],
            ],
            'subscriber' => [
                'name' => 'subscriber',
                'fullname' => 'Subscriber',
                'description' => 'Subscriber',
                'permissions' => [
                    'view-school',
                ],
            ],
            'dataentryuser' => [
                'name' => 'dataentryuser',
                'fullname' => 'Data Entry User',
                'description' => 'Data Entry User can access View Dashboard,Manage Colleges,Manage Universities,Manage Coupon Codes,View Coupon Code Claims',
                'permissions' => [
                    'view-school',
                    'create-school',
                    'edit-school',
                    'view-college',
                    'create-college',
                    'edit-college',
                    'view-universities',
                    'create-universities',
                    'edit-universities',
                    'view-field-agent',
                    'create-field-agent',
                    'edit-field-agent',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'view-hierarchy',
                ],
            ],
            'contentcreator' => [
                'name' => 'contentcreator',
                'fullname' => 'Content Creator',
                'description' => 'contentcreator',
                'permissions' => [
                    'view-faq_category',
                    'edit-faq_category',
                    'create-faq_category',
                    'view-downloadable-resource',
                    'create-downloadable-resource',
                    'edit-downloadable-resource',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'view-job-applications',
                    'create-job-applications',
                    'edit-job-applications',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'delete-blog-author',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                    'view-cloned-course',
                ],
            ],
            'contentlead' => [
                'name' => 'contentlead',
                'fullname' => 'Content Lead',
                'description' => 'contentlead',
                'permissions' => [
                    'view-videolist',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                    'view-webinar_category',
                    'edit-webinar_category',
                    'create-webinar_category',
                    'view-webinar',
                    'edit-webinar',
                    'create-webinar',
                    'create-batch',
                    'edit-batch',
                    'view-job-postings',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-blog-author',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'view-testimonials',
                    'create-testimonial',
                    'edit-testimonial',
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                    'create-orders',
                    'view-job-applications',
                    'edit-job-applications',
                    'view-enrollments',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'delete-hierarchy',
                    'view-enrollments',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'create-notification-settings',
                    'edit-notification-settings',
                    'view-downloadable-resource',
                    'create-downloadable-resource',
                    'edit-downloadable-resource',
                    'view-faq',
                    'view-cloned-course',
                ],
            ],
            'reviewer' => [
                'name' => 'reviewer',
                'fullname' => 'Reviewer',
                'description' => 'reviewer',
                'permissions' => [
                    'view-faq_category',
                    'edit-faq_category',
                    'create-faq_category',
                    'view-downloadable-resource',
                    'create-downloadable-resource',
                    'edit-downloadable-resource',
                    'view-article',
                    'create-article',
                    'edit-article',
                    'create-blog-author',
                    'edit-blog-author',
                    'view-article_category',
                    'edit-article_category',
                    'create-article_category',
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'view-package',
                    'view-enrollments',
                    'view-job-applications',
                    'create-job-applications',
                    'edit-job-applications',
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                    'view-current-affair_category',
                    'edit-current-affair_category',
                    'create-current-affair_category',
                    'view-current-affair',
                    'edit-current-affair',
                    'create-current-affair',
                    'delete-blog-author',
                    'view-job-postings',
                    'view-studymaterial',
                    'create-studymaterial',
                    'edit-studymaterial',
                ],
            ],
            'questioncreator' => [
                'name' => 'questioncreator',
                'fullname' => 'Question Creator',
                'description' => 'questioncreator',
                'permissions' => [
                    'view-hierarchy',
                    'create-hierarchy',
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                ],
            ],
            'ybu' => [
                'name' => 'ybu',
                'fullname' => 'Year Book User',
                'description' => 'ybu',
                'permissions' => [
                    'view-hierarchy',
                    'create-hierarchy',
                    'edit-hierarchy',
                    'view-enrollments',
                    'view-question_source',
                    'edit-question_source',
                    'create-question_source',
                ],
            ],
        ];
        foreach ($roles as $key => $role) {
            $create = Role::updateOrCreate(['name' => $key], [
                'fullname' => $role['fullname'],
                'description' => $role['description'],
            ]);
            $create->syncPermissions($role['permissions']);
        }
    }
}
